### ISSUE TITLE
CSRFInvalidationException when logging in

### ISSUE THREAD

**Issue by karashiiro** [karashiiro/Universalis#200]
Logging in via Discord returns a CSRFInvalidationException consistently. It's unclear what exactly is causing this, whether it's an issue with configuration on the Discord Developer Portal, on the server itself, or on some other layer. It worked at one point, so it's likely a server configuration issue.

**Comment by BenoitAnastay** [comment]
This condition return false 
```php
        // check CSRF
        if ($this->request->get('state') !== $this->request->getSession()->get('state')) {
            throw new CSRFInvalidationException();
        }
```
[SignInDiscord.php#L71](https://github.com/goaaats/common-php/blob/495d1b01a4a70546dea04ee453a1931652d3d823/User/SignInDiscord.php#L71)

**Comment by BenoitAnastay** [comment]
Server issue, nginx was not sending GET arguments to php-fpm
