### ISSUE TITLE
NotFoundHttpException on /docs

### ISSUE THREAD

**Issue by filliph** [karashiiro/Universalis#61]
https://universalis.app/about links to https://universalis.app/docs which produces

```
Symfony\Component\HttpKernel\Exception\NotFoundHttpException

e43468a7abd8273ce012aa39dd9cb8c4a67804f8
/docs
```

**Comment by karashiiro** [comment]
This one should go on https://github.com/goaaats/mogboard, but documentation hasn't been done yet besides. goat's been busy with getting uploader programs set up recently.

**Comment by karashiiro** [comment]
If you want the information now, the README on this repo has a fair bit of the information we're likely going to compile for that.

**Comment by karashiiro** [comment]
https://universalis.app/docs
This placeholder page resolves the error, still need to write the full documentation.
