### ISSUE TITLE
Slow performance when loading items

### ISSUE THREAD

**Issue by filliph** [karashiiro/Universalis#62]
This is using Chrome for Windows on a computer with 16 GB RAM.

![image](https://user-images.githubusercontent.com/9424286/64983537-9fe9ea00-d8b8-11e9-9fd3-1d57f7613421.png)

It took 10.7 seconds to load the actual page (before any of the scripts _on_ the page started to load), which is a bit excessive.

After initial load, there's an unknown period of time where reloading the page is instant, but after a while (might be approx. 5 minutes), load time is painfully slow again.

If needed I can keep experimenting with reloads to try to find the breakpoint.

**Comment by karashiiro** [comment]
This is also an issue for https://github.com/goaaats/mogboard , all of the lag time is in the PHP stuff, that 10.71 seconds. My guess is that it's downloading a lot of stuff from XIVAPI? Getting resources from the backend (this repo) shouldn't take more than a second. I'm not too familiar with the frontend though, so I can't say for certain where the bottleneck is.

Incidentally, we should probably figure out a better system for moving issues around :v I'll need to talk to goat about that. For this one I'll reference it myself.

**Comment by karashiiro** [comment]
Nevermind, there's no issues board there. I'll let goat know about this

**Comment by filliph** [comment]
If an issues board is opened, how would I know which issue goes where?

**Comment by karashiiro** [comment]
Issues relating to API calls and uploads would go here, and frontend issues would go there, probably. Actually, it might be better to field all issues here and let the appropriate person respond to them 🤔

**Comment by karashiiro** [comment]
I've added goat as a collaborator so goat can manage this directly

**Comment by filliph** [comment]
> Actually, it might be better to field all issues here and let the appropriate person respond to them

I would think so, given that this is the only GitHub link on the site, so people are going to be inspired to create any issues here 😅

**Comment by goaaats** [comment]
Loading new items will take this long, yeah - it needs to get the item from XivApi and cache it, technically though, consequent loads should be just fine time-wise. Can you check again?

**Comment by filliph** [comment]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/9424286/64999344-62e51e00-d8df-11e9-9749-6a10bbae8072.png">

As you can see, I have already visited the page for, f.ex. Flying Chair.

<img width="1504" alt="image" src="https://user-images.githubusercontent.com/9424286/64999449-b9eaf300-d8df-11e9-9d4f-770fea4f9000.png">

That page took nearly 5 seconds to generate.

I have also visited a few other pages:
<img width="684" alt="image" src="https://user-images.githubusercontent.com/9424286/64999461-cf601d00-d8df-11e9-97ff-bf38ae849963.png">

One of which took 7.49 seconds to generate:

<img width="654" alt="image" src="https://user-images.githubusercontent.com/9424286/64999508-f880ad80-d8df-11e9-9fc8-8e5870ffa0f1.png">

I don't think your cache is working 😝

**Comment by filliph** [comment]
It looks like the TTL on the item cache is < 5 minutes, as I just refreshed the 27786 page:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/9424286/64999744-d20f4200-d8e0-11e9-8e31-f111d14310f8.png">

**Comment by karashiiro** [comment]
#63 My bad 💯
