### ISSUE TITLE
"Something went wrong!"

### ISSUE THREAD

**Issue by filliph** [karashiiro/Universalis#63]
> Something went wrong!
200

> If you continue to run into this issue, please jump on the discord for help!

> GuzzleHttp\Exception\ConnectException
App\Controller\ItemController::index
bc545599ed5567a88eb5c30969a573c889cdcb48
/market/20791

![image](https://user-images.githubusercontent.com/9424286/65168818-3b0bcc80-da3d-11e9-8983-08d1421c529b.png)

Probably related to #62 (since you don't appear to actually permanently cache item info from XIVAPI).

**Comment by karashiiro** [comment]
Been looking into it for the past half-hour or so, can confirm that it's not a CPU or memory issue, though memory usage _is_ much higher than yesterday (request overhead from Teamcraft?).

**Comment by karashiiro** [comment]
Once again, API doesn't seem to be affected, so it's either mogboard or server configuration.

**Comment by filliph** [comment]
The Teamcraft update is not live yet, so it cannot be that.

I also randomly got this using your ACT plugin, accompanied by a 504 Gateway Timeout error from Cloudflare on the site itself:
```
[ERROR] Market Board data upload failed:
System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at Dalamud.Game.Network.Universalis.MarketBoardUploaders.UniversalisMarketBoardUploader.Upload(MarketBoardItemRequest request)
   at UniversalisPlugin.PluginSample.DataSubscriptionOnNetworkReceived(String connection, Int64 epoch, Byte[] message)
```

**Comment by karashiiro** [comment]
In that case, the memory usage increase could be a memory leak. I'll restart the system and see if that fixes it.

**Comment by karashiiro** [comment]
Alright, server's been restarted completely. Items that were broken before seem to be working now.

**Comment by filliph** [comment]
Hate to be the bearer of bad news...

![image](https://user-images.githubusercontent.com/9424286/65169966-9b9c0900-da3f-11e9-8e9c-173533f03d90.png)

**Comment by karashiiro** [comment]
(ik you're in Discord, but just for documentation purposes)
For future reference, MongoDB indices were not set up; I had dropped them and forgot to restore them when we switched to production mode.
